### ISSUE TITLE
does not work with jQuery 2.1.3

### ISSUE THREAD

**Issue by artknight** [rkusa/touch-dnd#18]
When i do $('.draggable').draggable() i get "TypeError: undefined is not a function"
